/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author USER
 */
public class Account_Information extends javax.swing.JFrame {

    /**
     * Creates new form Account_Information
     */
    
    private String cus_id_str;
    private int acc_no;
    public Account_Information(String cus_id_str) {
        initComponents();
        this.setTitle("Account Information");
        this.cus_id_str = cus_id_str;
        String sql = "SELECT * FROM Accounts WHERE Customer_id = ?";
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PRESENT;user=sa;password=sa;encrypt=true;trustServerCertificate=true");

            // Use prepared statement to avoid SQL injection
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, cus_id_str);
            
            System.out.println(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String customer_id = rs.getString("customer_id");
                BigDecimal balance = rs.getBigDecimal("balance").setScale(2, RoundingMode.HALF_EVEN);
                int acc_no_get = rs.getInt("Account_No");
                
                this.acc_no = acc_no_get;
                txtBalance.setText(balance.toString());
                txtBalance.setEditable(false);

                txtAccNo.setEditable(false);
                txtAccNo.setText(String.valueOf(acc_no_get));

                txtCustomer_id.setText(this.cus_id_str);
                txtCustomer_id.setEditable(false);

            }

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Database driver not found.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while accessing the database.");
        }

    }
    //overload
    public Account_Information(int accno) {
        initComponents();
 
        String sql = "SELECT * FROM Accounts WHERE Account_No = ? ";
        System.out.println(sql);
        try (Connection conn = DatabaseAccess.getConnection();
               PreparedStatement pst = conn.prepareStatement(sql)) {
               pst.setInt(1, accno);
            
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String customer_id = rs.getString("customer_id");
                BigDecimal balance = rs.getBigDecimal("balance").setScale(2, RoundingMode.HALF_EVEN);
                int acc_no_get = rs.getInt("Account_No");
                
                this.cus_id_str = customer_id;
                this.acc_no = acc_no_get;
                SwingUtilities.invokeLater(() -> {
                    txtBalance.setText(balance.toString());
                    txtBalance.setEditable(false);

                    txtAccNo.setEditable(false);
                    txtAccNo.setText(String.valueOf(acc_no_get));

                    txtCustomer_id.setText(this.cus_id_str);
                    txtCustomer_id.setEditable(false);
                });


            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while accessing the database.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnBackToMain = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        CheckSavingAcc = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCustomer_id = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("ACCOUNT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 310, 90));

        btnBackToMain.setBackground(new java.awt.Color(0, 153, 0));
        btnBackToMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToMain.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToMain.setText("Back to home screen");
        btnBackToMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBackToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackToMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 190, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Current Balance:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Account number:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        txtAccNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAccNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccNo.setToolTipText("");
        txtAccNo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtAccNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 170, 40));

        txtBalance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBalance.setToolTipText("");
        txtBalance.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 170, 40));

        CheckSavingAcc.setBackground(new java.awt.Color(0, 153, 0));
        CheckSavingAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckSavingAcc.setForeground(new java.awt.Color(255, 255, 255));
        CheckSavingAcc.setText("Check saving accounts");
        CheckSavingAcc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CheckSavingAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckSavingAccActionPerformed(evt);
            }
        });
        getContentPane().add(CheckSavingAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 190, 40));

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Create saving accounts");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 190, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("CustomerID: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        txtCustomer_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCustomer_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCustomer_id.setToolTipText("");
        txtCustomer_id.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtCustomer_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 170, 40));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMainActionPerformed
        setVisible(false);
        MainPage main = new MainPage(cus_id_str);
        main.setVisible(true);
        main.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_btnBackToMainActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        CreateSaving create = new CreateSaving(acc_no);
        create.setVisible(true);
        create.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CheckSavingAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckSavingAccActionPerformed
        try {
            
            var check = new CheckSaving(acc_no);
            check.setVisible(true);
            this.setVisible(false);
            check.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(Account_Information.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_CheckSavingAccActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckSavingAcc;
    private javax.swing.JButton btnBackToMain;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCustomer_id;
    // End of variables declaration//GEN-END:variables
}
