/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    private String cus_id;
    
    public MainPage(String cus_id) {
    initComponents();
    this.setTitle("Main");
    this.cus_id = cus_id;
    String sql = "SELECT fullname FROM Customer WHERE customer_id=?";
    System.out.println(sql);
    try (Connection conn = DatabaseAccess.getConnection();
     PreparedStatement pst = conn.prepareStatement(sql)) {
        pst.setString(1, cus_id);
        
        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            String fullname = rs.getString(1);
            txtHelloUser.setText("Welcome " + fullname +" !!! ");
            txtHelloUser.setEditable(false);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGoToTransaction = new javax.swing.JButton();
        btnGoToAccount_Info = new javax.swing.JButton();
        btnGoToHistory = new javax.swing.JButton();
        txtHelloUser = new javax.swing.JTextField();
        btnCustomerDetails = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setBackground(new java.awt.Color(0, 153, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit.setDefaultCapable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 110, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Main Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 340, 90));

        btnGoToTransaction.setBackground(new java.awt.Color(0, 153, 0));
        btnGoToTransaction.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGoToTransaction.setForeground(new java.awt.Color(255, 255, 255));
        btnGoToTransaction.setText("Transit");
        btnGoToTransaction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGoToTransaction.setDefaultCapable(false);
        btnGoToTransaction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoToTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToTransactionActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoToTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 210, 50));

        btnGoToAccount_Info.setBackground(new java.awt.Color(0, 153, 0));
        btnGoToAccount_Info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGoToAccount_Info.setForeground(new java.awt.Color(255, 255, 255));
        btnGoToAccount_Info.setText("Account");
        btnGoToAccount_Info.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGoToAccount_Info.setDefaultCapable(false);
        btnGoToAccount_Info.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoToAccount_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToAccount_InfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoToAccount_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 210, 50));

        btnGoToHistory.setBackground(new java.awt.Color(0, 153, 0));
        btnGoToHistory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGoToHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnGoToHistory.setText("Transaction History");
        btnGoToHistory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGoToHistory.setDefaultCapable(false);
        btnGoToHistory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoToHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoToHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 210, 50));

        txtHelloUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtHelloUser.setForeground(new java.awt.Color(0, 204, 0));
        txtHelloUser.setText("jTextField1");
        txtHelloUser.setHighlighter(null);
        txtHelloUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHelloUserActionPerformed(evt);
            }
        });
        getContentPane().add(txtHelloUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 320, 40));

        btnCustomerDetails.setBackground(new java.awt.Color(0, 153, 0));
        btnCustomerDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCustomerDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomerDetails.setText("Customer Details");
        btnCustomerDetails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCustomerDetails.setDefaultCapable(false);
        btnCustomerDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCustomerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnCustomerDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 210, 50));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
          this.dispose();
          Login frm = new Login();
            frm.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnGoToTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToTransactionActionPerformed
        setVisible(false);
        Transaction trans = new Transaction(cus_id);
        trans.setVisible(true);
        trans.setLocationRelativeTo(null);
        trans.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnGoToTransactionActionPerformed

    private void btnGoToHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToHistoryActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        History history = new History(cus_id);
        history.setVisible(true);
        history.setLocationRelativeTo(null);
        history.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnGoToHistoryActionPerformed

    private void btnGoToAccount_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToAccount_InfoActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Account_Information acc = new Account_Information(cus_id);
        acc.setVisible(true);
        acc.setLocationRelativeTo(null);
        acc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnGoToAccount_InfoActionPerformed

    private void txtHelloUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHelloUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHelloUserActionPerformed

    private void btnCustomerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerDetailsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        CustomerDetails cus = new CustomerDetails(cus_id);
        cus.setVisible(true);
        cus.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnCustomerDetailsActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerDetails;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGoToAccount_Info;
    private javax.swing.JButton btnGoToHistory;
    private javax.swing.JButton btnGoToTransaction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtHelloUser;
    // End of variables declaration//GEN-END:variables

    private JTextField getText(String fullname) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
