/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking;

import com.toedter.calendar.JDateChooser;
import java.awt.HeadlessException;
import static java.awt.SystemColor.window;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JFrame;

/**
 *
 * @author asus
 */
public class SignUp extends javax.swing.JFrame {
    JDateChooser dateChooser;
    
    /**
     * Creates new form signup
     */
    public SignUp() {
        initComponents();
                this.setTitle("Sign Up");

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fname = new javax.swing.JTextField();
        ema = new javax.swing.JTextField();
        conno = new javax.swing.JTextField();
        addr = new javax.swing.JTextField();
        dob_field = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addr1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        PIN = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rePIN = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Register Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Name :*");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 80, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Email: *");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Gender: *");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 130, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Date of birth: *");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 130, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Contact Number: *");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 130, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText("City: *");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 120, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 110, 30));

        fname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 260, -1));

        ema.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(ema, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 260, -1));

        conno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(conno, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 190, -1));

        addr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 190, -1));

        dob_field.setForeground(new java.awt.Color(0, 204, 0));
        getContentPane().add(dob_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 160, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 0));
        jLabel9.setText("Already have an account? Log in");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Street : *");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 120, -1));

        addr1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addr1ActionPerformed(evt);
            }
        });
        getContentPane().add(addr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 190, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Other", "Not Prefer" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 0));
        jLabel10.setText("Password *");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 120, -1));

        PIN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(PIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 260, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setText("Verify Password*");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 140, -1));

        rePIN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rePIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rePINActionPerformed(evt);
            }
        });
        getContentPane().add(rePIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 260, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                         
    String fullname = fname.getText();
    String email = ema.getText();
    String contactnumber = conno.getText();
    String City = addr.getText();
    String Street = addr1.getText();
    String Gender = jComboBox1.getSelectedItem().toString();
    String pass = PIN.getText();
    String repass = rePIN.getText();
    java.util.Date dob = dob_field.getDate();

    // Check if passwords match
    if (!repass.equals(pass)) {
        JOptionPane.showMessageDialog(null, "Passwords do not match");
        dispose();
        return;
    }
    if (pass.length() > 6) {
    JOptionPane.showMessageDialog(null, "Password must be 6 characters long");
    dispose();
    return;
    }
    
    if (dob == null) {
    JOptionPane.showMessageDialog(null, "Please enter your date of birth");
    dispose();
    return;
    }

    // Check if required fields are filled
    if (fname.getText().isEmpty() || ema.getText().isEmpty() || conno.getText().isEmpty() || addr.getText().isEmpty() || addr1.getText().isEmpty() || Gender.equals("Select Gender") || pass.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Fill all the * fields");
        return;
    }

    String customerSql = "INSERT INTO Customer (fullname, email, Contact_number, City, Street, Gender, date_of_birth, PIN) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
    String accountSql = "INSERT INTO Accounts (balance, Open_date, customer_id) VALUES (0.00, GETDATE(), ?)";
    System.out.println(accountSql);
    System.out.println(customerSql);
    try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        try (Connection conn = DatabaseAccess.getConnection();
             PreparedStatement customerPst = conn.prepareStatement(customerSql, PreparedStatement.RETURN_GENERATED_KEYS);
             PreparedStatement accountPst = conn.prepareStatement(accountSql)) {

            conn.setAutoCommit(false);  // Start transaction

            customerPst.setString(1, fullname);
            customerPst.setString(2, email);
            customerPst.setString(3, contactnumber);
            customerPst.setString(4, City);
            customerPst.setString(5, Street);
            customerPst.setString(6, Gender);
            customerPst.setDate(7, new java.sql.Date(dob.getTime()));
            customerPst.setString(8, pass);

            int rowsAffected = customerPst.executeUpdate();

            if (rowsAffected > 0) {
                // Retrieve the auto-generated key (customer_id)
                try (ResultSet generatedKeys = customerPst.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        int customerId = generatedKeys.getInt(1);

                        // Insert into the accounts table with the generated customer_id
                        accountPst.setInt(1, customerId);
                        int accountRowsAffected = accountPst.executeUpdate();

                        if (accountRowsAffected > 0) {
                            conn.commit();  // Commit transaction
                            JOptionPane.showMessageDialog(null, "Sign up successful! Account created with customer_id: " + customerId);
                            this.setVisible(false);
                            Login log = new Login();
                            log.setVisible(true);
                            log.setLocationRelativeTo(null);
                           
                        } else {
                            conn.rollback();  // Rollback transaction if account creation fails
                            JOptionPane.showMessageDialog(null, "Sign up unsuccessful! Unable to create account.");
                            dispose();
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Sign up unsuccessful!");
                dispose();
                setVisible(false);
                Login log = new Login();
                log.setVisible(true);
                log.setLocationRelativeTo(null);
                log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
        }
    } catch (HeadlessException | ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(null, e);
    }



    }//GEN-LAST:event_jButton1ActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        setVisible(false);
        Login log = new Login();
        log.setVisible(true);
                log.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void addr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addr1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void rePINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rePINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rePINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SignUp sign = new SignUp();
                sign.setVisible(true);
                sign.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PIN;
    private javax.swing.JTextField addr;
    private javax.swing.JTextField addr1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField conno;
    private com.toedter.calendar.JDateChooser dob_field;
    private javax.swing.JTextField ema;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField rePIN;
    // End of variables declaration//GEN-END:variables
}
