/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking;

import java.awt.HeadlessException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */

    public class Transaction extends javax.swing.JFrame {
        
        private int cus_id;
        private int my_acc_no;
        private BigDecimal my_balance;
        private String cus_id_str;
      
        
        public Transaction(String cus_id_str) {
            initComponents();
            this.setTitle("Transit");
        this.cus_id_str = cus_id_str;
        this.cus_id = Integer.parseInt(cus_id_str);
        String sql = "SELECT Account_No, balance FROM Accounts WHERE customer_id= ? ";

        try (Connection conn = DatabaseAccess.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql)) {

            pst.setInt(1, cus_id);
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    int accountNo = rs.getInt("Account_No");
                    BigDecimal balance = rs.getBigDecimal("balance");

                    my_acc_no = accountNo;
                    my_balance = balance;
                }

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtOtherAcc_No = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAmountSelected = new javax.swing.JTextField();
        btnTransit = new javax.swing.JButton();
        btnBackToMain = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setSize(200,100);
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Transaction");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Amount:");

        txtOtherAcc_No.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtOtherAcc_No.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOtherAcc_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtherAcc_NoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("To Account Number:");

        txtAmountSelected.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAmountSelected.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAmountSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountSelectedActionPerformed(evt);
            }
        });

        btnTransit.setBackground(new java.awt.Color(0, 153, 0));
        btnTransit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTransit.setForeground(new java.awt.Color(255, 255, 255));
        btnTransit.setText("Transit");
        btnTransit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTransit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransitActionPerformed(evt);
            }
        });

        btnBackToMain.setBackground(new java.awt.Color(0, 153, 0));
        btnBackToMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToMain.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToMain.setText("Back to home screen");
        btnBackToMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBackToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnTransit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnBackToMain))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAmountSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOtherAcc_No, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOtherAcc_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmountSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMainActionPerformed

        setVisible(false);
        MainPage main = new MainPage(cus_id_str);
        main.setVisible(true);
        main.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnBackToMainActionPerformed

    private void btnTransitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransitActionPerformed
        try (Connection conn = DatabaseAccess.getConnection()) {
            String otherAccNoStr = txtOtherAcc_No.getText();
            int otherAccNo;
            try {
                otherAccNo = Integer.parseInt(otherAccNoStr);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Invalid Account Number");
                return;
            }

            BigDecimal amountSelected;
            try {
                amountSelected = new BigDecimal(txtAmountSelected.getText()).setScale(2, RoundingMode.HALF_EVEN);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Invalid Amount");
                return;
            }

            String sql = "SELECT Account_No, Balance  FROM Accounts WHERE Account_No= ?";
            System.out.println(sql);
            try (PreparedStatement pst = conn.prepareStatement(sql)) {
                pst.setInt(1, otherAccNo);
                    
                try (ResultSet rs = pst.executeQuery()) {
                    if (rs.next()) {
                        
                        if (my_acc_no == otherAccNo) {
                            JOptionPane.showMessageDialog(null, "Invalid Account");
                            return;
                        }

                        if (my_balance.compareTo(amountSelected) >= 0) {
                            String updateSql1 = "UPDATE Accounts SET Balance = Balance + ? WHERE Account_No = ?";
                            System.out.println(updateSql1);
                            try (PreparedStatement updatePst1 = conn.prepareStatement(updateSql1)) {
                                updatePst1.setBigDecimal(1, amountSelected);
                                updatePst1.setInt(2, otherAccNo);
                                updatePst1.executeUpdate();
                            }

                            String updateSql2 = "UPDATE Accounts SET Balance = Balance - ? WHERE Account_No = ?";
                            System.out.println(updateSql2);
                            try (PreparedStatement updatePst2 = conn.prepareStatement(updateSql2)) {
                                updatePst2.setBigDecimal(1, amountSelected);
                                updatePst2.setInt(2, my_acc_no);
                                updatePst2.executeUpdate();
                            }

                            String insertSQL = "INSERT INTO [new_transaction] (Amount, transaction_date, customer_id) VALUES (?, GETDATE(), ?)";
                            System.out.println(insertSQL);
                            try (PreparedStatement insertPst = conn.prepareStatement(insertSQL, PreparedStatement.RETURN_GENERATED_KEYS)) {
                                insertPst.setBigDecimal(1, amountSelected);
                                insertPst.setString(2, cus_id_str);
                                insertPst.executeUpdate();

                                try (ResultSet generatedKeys = insertPst.getGeneratedKeys()) {
                                    if (generatedKeys.next()) {
                                        int transaction_id = generatedKeys.getInt(1);
                                        System.out.println("Generated Transaction ID: " + transaction_id);
                                    }
                                }
                            }

                            JOptionPane.showMessageDialog(null, "Transaction completed.");
                            setVisible(false);
                            MainPage main = new MainPage(cus_id_str);
                            main.setVisible(true);
                            main.setLocationRelativeTo(null);
                        } else {
                            JOptionPane.showMessageDialog(null, "Insufficient balance for the transaction.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Transaction");
                    }
                }
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnTransitActionPerformed

    private void txtAmountSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountSelectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountSelectedActionPerformed

    private void txtOtherAcc_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtherAcc_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtherAcc_NoActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        setVisible(false);

    }//GEN-LAST:event_jLabel1MouseClicked
    
   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMain;
    private javax.swing.JButton btnTransit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAmountSelected;
    private javax.swing.JTextField txtOtherAcc_No;
    // End of variables declaration//GEN-END:variables
    }